### ISSUE TITLE
Error while import opencog python libraries

### ISSUE THREAD

**Issue by Habush** [opencog/docker#125]
I have a docker image which uses the [opencog-dev](https://hub.docker.com/r/opencog/opencog-dev/) image as a base. After building the image successfully, I can't use the OpenCog python modules as I run into an import error. The docker files I am using to build the images can be found at this [repo](https://github.com/Habush/mozi_docker). As an example, running this simple script on the python command line raises an import error
```
from opencog.atomspace import AtomSpace
atomspace = AtomSpace()
```
The error:

`ImportError: No module named opencog.atomspace`

**Comment by AmeBel** [comment]
@Habush fixed by https://github.com/opencog/ocpkg/pull/102

**Comment by Habush** [comment]
@AmeBel The error is still occurring. Also the default python version is 2.7

**Comment by AmeBel** [comment]
@Habush In the docker containers it is python3. Do you want a python 2 version?

**Comment by mjsduncan** [comment]
the mozi back-end is currently using python 2.  is there a way to force atomspace/opencog to be built with python 3?

**Comment by AmeBel** [comment]
@Habush @misgeatgit the opencog/X images are not meant only for development and not for production systems

**Comment by linas** [comment]
If a system has both python2 and python3 installed. does opencog build both versions?  It probably should; they could be build in different directories, adn installed in different install locations.

**Comment by AmeBel** [comment]
@linas CMake is not configured to do that presently, but yes that is possible.

**Comment by linas** [comment]
porting to python3 should not be hard, there are several great "howto" pages out there -- its mostly just tedious, like adding extra parens to print statements, etc.
